### PR TITLE
Wazo 3405 delete moh

### PR DESCRIPTION
**Pull request by xxbillouxx**
must be merged after https://github.com/wazo-platform/xivo-manage-db/pull/230

Depends-On: https://github.com/wazo-platform/wazo-sysconfd/pull/90

### CODE REVIEW

**Comment by xxbillouxx** [comment]
recheck

**Comment by DrPyser** [comment]
The integration test failure seems unrelated to this PR:
```
======================================================================
FAIL: suite.base.test_provisioning_networking.test_put_minimal_parameters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zuul-worker/src/github.com/wazo-platform/wazo-confd/.tox/integration/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/zuul-worker/src/github.com/wazo-platform/wazo-confd/integration_tests/suite/base/test_provisioning_networking.py", line 48, in test_put_minimal_parameters
    assert_that(
AssertionError: 
Expected: a dictionary containing {'provision_host': '', 'provision_http_base_url': '', 'provision_http_port': <18667>}
     but: value for 'provision_http_port' was <8667>
 ```

**Comment by DrPyser** [comment]
The integration test failure seems unrelated to this PR:
```
======================================================================
FAIL: suite.base.test_provisioning_networking.test_put_minimal_parameters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/zuul-worker/src/github.com/wazo-platform/wazo-confd/.tox/integration/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/zuul-worker/src/github.com/wazo-platform/wazo-confd/integration_tests/suite/base/test_provisioning_networking.py", line 48, in test_put_minimal_parameters
    assert_that(
AssertionError: 
Expected: a dictionary containing {'provision_host': '', 'provision_http_base_url': '', 'provision_http_port': <18667>}
     but: value for 'provision_http_port' was <8667>
 ```

**Comment by DrPyser** [comment]
recheck

**Comment by fblackburn1** [comment]
Yes will be fixed by:
Depends-on: https://github.com/wazo-platform/wazo-confd/pull/421

**Review by DrPyser — APPROVED** [review]
Well done!

**Pull request merged**
