### PR TITLE
Pull request for WAZO-2635-meeting-authorization

### PR DESCRIPTION
**Pull request by sduthil**
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/156
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/48
Depends-On: https://github.com/wazo-platform/wazo-test-helpers/pull/70
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/170

## meetings: add authorization acceptation

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Review by pc-m — APPROVED** [review]

**Comment by pc-m** [comment]
regate

**Comment by pc-m** [comment]
regate

**Comment by sduthil** [comment]
regate

**Comment by sduthil** [comment]
regate

**Comment by sduthil** [comment]
recheck

**Pull request merged**
