### PR TITLE
Add func_key_dest_conf in tests when deleting tenant

### PR DESCRIPTION
**Pull request by xxbillouxx**
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/250
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/237

### CODE REVIEW

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by DrPyser** [comment]
```
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]: Traceback (most recent call last):
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/wazo_confd/helpers/common.py", line 28, in wrapper
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return func(*args, **kwargs)
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/xivo/auth_verifier.py", line 226, in wrapper
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return func(*args, **kwargs)
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/xivo/auth_verifier.py", line 191, in wrapper
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return func(*args, **kwargs)
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/wazo_confd/plugins/func_key/resource.py", line 112, in get
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     'items': [
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/wazo_confd/plugins/func_key/resource.py", line 113, in <listcomp>
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     self.schema(context=self.context).dump(item) for item in result.items
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/schema.py", line 559, in dump
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     result = self._serialize(processed_obj, many=many)
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/schema.py", line 523, in _serialize
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/fields.py", line 330, in serialize
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return self._serialize(value, attr, obj, **kwargs)
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/wazo_confd/plugins/func_key/schema.py", line 298, in _serialize
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     funckey = self.nested_field.serialize(raw_position, getattr(obj, attr))
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/fields.py", line 330, in serialize
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return self._serialize(value, attr, obj, **kwargs)
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/fields.py", line 585, in _serialize
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return schema.dump(nested_obj, many=many)
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/schema.py", line 559, in dump
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     result = self._serialize(processed_obj, many=many)
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/schema.py", line 523, in _serialize
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/fields.py", line 330, in serialize
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return self._serialize(value, attr, obj, **kwargs)
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/wazo_confd/plugins/func_key/schema.py", line 257, in _serialize
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     self.destination_schemas[base['type']], unknown=self.unknown
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]: TypeError: 'NoneType' object is not subscriptable
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]: 2023-11-08 16:41:23,448 [1426106] (INFO) (wazo_confd): response to 10.0.4.40 in 0.08s: GET https://172.16.43.238/api/confd/1.1/funckeys/templates?direction=asc&>
Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]: 2023-11-08 16:41:23,449 [1426106] (DEBUG) (wazo_confd): response body: ["Unexpected error: 'NoneType' object is not subscriptable"]
```
Seeing this error when testing the deletion of a conference with a func key template pointing to it.

**Comment by DrPyser** [comment]
> ```
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]: Traceback (most recent call last):
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/wazo_confd/helpers/common.py", line 28, in wrapper
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return func(*args, **kwargs)
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/xivo/auth_verifier.py", line 226, in wrapper
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return func(*args, **kwargs)
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/xivo/auth_verifier.py", line 191, in wrapper
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return func(*args, **kwargs)
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/wazo_confd/plugins/func_key/resource.py", line 112, in get
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     'items': [
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/wazo_confd/plugins/func_key/resource.py", line 113, in <listcomp>
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     self.schema(context=self.context).dump(item) for item in result.items
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/schema.py", line 559, in dump
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     result = self._serialize(processed_obj, many=many)
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/schema.py", line 523, in _serialize
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/fields.py", line 330, in serialize
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return self._serialize(value, attr, obj, **kwargs)
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/wazo_confd/plugins/func_key/schema.py", line 298, in _serialize
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     funckey = self.nested_field.serialize(raw_position, getattr(obj, attr))
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/fields.py", line 330, in serialize
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return self._serialize(value, attr, obj, **kwargs)
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/fields.py", line 585, in _serialize
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return schema.dump(nested_obj, many=many)
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/schema.py", line 559, in dump
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     result = self._serialize(processed_obj, many=many)
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/schema.py", line 523, in _serialize
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/marshmallow/fields.py", line 330, in serialize
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     return self._serialize(value, attr, obj, **kwargs)
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:   File "/usr/lib/python3/dist-packages/wazo_confd/plugins/func_key/schema.py", line 257, in _serialize
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]:     self.destination_schemas[base['type']], unknown=self.unknown
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]: TypeError: 'NoneType' object is not subscriptable
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]: 2023-11-08 16:41:23,448 [1426106] (INFO) (wazo_confd): response to 10.0.4.40 in 0.08s: GET https://172.16.43.238/api/confd/1.1/funckeys/templates?direction=asc&>
> Nov 08 16:41:23 wazo-stack-dev wazo-confd[1426106]: 2023-11-08 16:41:23,449 [1426106] (DEBUG) (wazo_confd): response body: ["Unexpected error: 'NoneType' object is not subscriptable"]
> ```
> 
> Seeing this error when testing the deletion of a conference with a func key template pointing to it.

I think that's because there's another missing delete cascade from `func_key_dest_conference` to `func_key`:
```
"func_key_dest_conference_func_key_id_fkey" FOREIGN KEY (func_key_id, destination_type_id) REFERENCES func_key(id, destination_type_id)
```

**Comment by DrPyser** [comment]
There's also the table `func_key_mapping` that points to `func_key` and has no delete cascade.

**Comment by DrPyser** [comment]
I think integration tests should be added to properly cover the deletion of conference with phone key pointing to it.

**Comment by xxbillouxx** [comment]
recheck

**Comment by DrPyser** [comment]
recheck

**Comment by DrPyser** [comment]
I'm seeing an error when running the `test_tenants` tests:
```
ERROR: test_delete_tenant_with_many_resources_by_syncdb (suite.base.test_tenants.BaseTestDeleteBySyncDb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/drpyser/wazo/wazo-confd/integration_tests/suite/helpers/wrappers.py", line 81, in decorated
    result = func(*new_args, **kwargs)
  File "/home/drpyser/wazo/wazo-confd/integration_tests/suite/helpers/wrappers.py", line 81, in decorated
    result = func(*new_args, **kwargs)
  File "/home/drpyser/wazo/wazo-confd/integration_tests/suite/helpers/wrappers.py", line 81, in decorated
    result = func(*new_args, **kwargs)
  [Previous line repeated 23 more times]
  File "/home/drpyser/wazo/wazo-confd/integration_tests/suite/base/test_tenants.py", line 416, in test_delete_tenant_with_many_resources_by_syncdb
    aux()
  File "/home/drpyser/wazo/wazo-confd/integration_tests/suite/helpers/wrappers.py", line 81, in decorated
    result = func(*new_args, **kwargs)
  File "/home/drpyser/wazo/wazo-confd/integration_tests/suite/helpers/wrappers.py", line 81, in decorated
    result = func(*new_args, **kwargs)
  File "/home/drpyser/wazo/wazo-confd/integration_tests/suite/helpers/wrappers.py", line 81, in decorated
    result = func(*new_args, **kwargs)
  [Previous line repeated 3 more times]
  File "/home/drpyser/wazo/wazo-confd/integration_tests/suite/base/test_tenants.py", line 383, in aux
    with (
AttributeError: __enter__
```

**Review by DrPyser — APPROVED** [review]
All good

**Pull request merged**
