### PR TITLE
Revamp user sub-resources

### PR DESCRIPTION
**Pull request by xxbillouxx**
Put sub-resources classes and schemas in dedicated package. 

This is most consistent with the way schemas and resources are stored in the other plugins: 
- one file for resources definitions (resource.py)
- one file for schemas definitions (schema.py)

### CODE REVIEW

**Review by pc-m — APPROVED** [review]

**Review by fblackburn1 — APPROVED** [review]
LGTM
Note: resources in confd are not plural, so it's weird to have sub_resources with an `s` ... but nobody will notice :joy:

**Comment by xxbillouxx** [comment]
> LGTM Note: resources in confd are not plural, so it's weird to have sub_resources with an `s` ... but nobody will notice 😂

There are many "sub-resources" related to the user (implemented in sub_resources/resource.py): UserServiceDND, UserForwardBusy, ... This is the reason 😄

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Pull request merged**
