### PR TITLE
switchboard: add moh fields

### PR DESCRIPTION
**Pull request by pc-m**
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/123
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/119

### CODE REVIEW

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
Zuul pulls the old DB image after building the new one.

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
In the spec, the name is "waiting_music_on_hold" not "waiting_room_music_on_hold"

**Comment by pc-m** [comment]
> In the spec, the name is "waiting_music_on_hold" not "waiting_room_music_on_hold"



> In the spec, the name is "waiting_music_on_hold" not "waiting_room_music_on_hold"

fixed

**Pull request merged**
