### PR TITLE
WAZO-2059-refactor-online-call-record

### PR DESCRIPTION
**Pull request by sduthil**
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/101
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/98
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/99/files

### CODE REVIEW

**Comment by pc-m** [comment]
recheck

**Comment by sduthil** [comment]
Tests should be fixed, but they may fail because Depends-On is not applied correctly...

**Comment by sduthil** [comment]
recheck

**Review by pc-m — APPROVED** [review]

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
> Build succeeded.
> 
> * [tox-linters ](https://zuul.wazo.community/logs/74/174/8d270e7774608e46d5c8430a7b52dc7ae5604acc/check/tox-linters/f84fd02/) : SUCCESS in 9m 54s
> * [wazo-tox-py37 ](https://zuul.wazo.community/logs/74/174/8d270e7774608e46d5c8430a7b52dc7ae5604acc/check/wazo-tox-py37/392e9c8/) : SUCCESS in 10m 25s
> * [debian-packaging ](https://zuul.wazo.community/logs/74/174/8d270e7774608e46d5c8430a7b52dc7ae5604acc/check/debian-packaging/2514bca/) : SUCCESS in 9m 47s
> * [confd-tox-integration ](https://zuul.wazo.community/logs/74/174/8d270e7774608e46d5c8430a7b52dc7ae5604acc/check/confd-tox-integration/ca015c6/) : SUCCESS in 45m 56s

FINALLY

**Comment by pc-m** [comment]
regate

**Pull request merged**
