### PR TITLE
Update version for marshmallow and pyyaml

### PR DESCRIPTION
**Pull request by xxbillouxx**
To prepare the potential use of https://apispec.readthedocs.io/en/latest/
And to keep marshmallow and pyyaml with the latest versions

### CODE REVIEW

**Review by pc-m — CHANGES_REQUESTED** [review]
Wazo currently uses Debian Buster. Debian Bullseye soon. In a couple years we will use Debian Bookworm.

Bookworm will provide the following version.
marshmallow 3.18.0
pyyaml 6.0

In the mean time, you would have to package marshmallow and pyyaml for Debian Buster.

Here are some links to see how that can be done.
https://github.com/wazo-platform/wazo-python-fastapi-packaging
https://github.com/wazo-platform/xivo-build-tools/blob/master/etc/xivo-build-tools/packages#L73
https://jenkins.wazo.community/job/wazo-python-fastapi-packaging/
https://wiki.wazo.io/en/processes/checklist_new_repo

**Comment by fblackburn1** [comment]
Also note that you **must** use the same version for **all** repos/services
And **should** use the same version for **all** project used by Wazo

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
I'm closing this PR, as there is no easy way to update python dependencies.

**Pull request closed without merging**
