### PR TITLE
tests: reproduced non-linked destination issue

### PR DESCRIPTION
**Pull request by sileht**
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/21

### CODE REVIEW

**Comment by sileht** [comment]
recheck

**Comment by fblackburn1** [comment]
In general if you want to do this kind of test, use the resource in xivo-dao
Ex:
https://github.com/wazo-platform/xivo-dao/blob/master/xivo_dao/resources/ivr/tests/test_dao.py#L295

**Comment by sileht** [comment]
> This fix as nothing to do with wazo-confd, it's purely a database coherence

The bug was report with a chain of API calls to do, so I write the same chain in tests to understand what happen.

Then, I wrote another minimal test in xivo-dao that trigger the bug too: https://github.com/wazo-platform/xivo-dao/pull/22/files#diff-50d0dd21dde6c97ee3f912187f78c412R108

I will move it in xivo_dao/resources/incall/tests/test_dao.py as your recommend tomorrow.

We can close that one if you thing this new tests does worse to be kept

**Comment by fblackburn1** [comment]
> Then, I wrote another minimal test in xivo-dao that trigger the bug too: https://github.com/wazo-platform/xivo-dao/pull/22/files#diff-50d0dd21dde6c97ee3f912187f78c412R108
> 
> I will move it in xivo_dao/resources/incall/tests/test_dao.py as your recommend tomorrow.
> 
> We can close that one if you thing this new tests does worse to be kept

No need to move the test, since the logic is in the sqlalchemy schema, its totally fine

**Pull request closed without merging**
