### PR TITLE
WAZO-2920-line-extension

### PR DESCRIPTION
**Pull request by pc-m**

### CODE REVIEW

**Review by xxbillouxx — APPROVED** [review]
LGTM

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
* To be coherent with our endpoint_sip implementation, we should populate `context` for extension when it's already provided by the line body
* openapi is missing
* changelog is missing

**Review by fblackburn1 — DISMISSED** [review]

**Comment by pc-m** [comment]
I added `auto-merge` because I executed `black` after you approval

**Comment by fblackburn1** [comment]
```
confd_base-confd-1     | 2022-11-09 14:52:06,894 [1] (ERROR) (wazo_confd.helpers.common): 'context'
confd_base-confd-1     | Traceback (most recent call last):
confd_base-confd-1     |   File "/usr/src/wazo-confd/wazo_confd/helpers/common.py", line 28, in wrapper
confd_base-confd-1     |     return func(*args, **kwargs)
confd_base-confd-1     |   File "/opt/venv/lib/python3.7/site-packages/xivo/auth_verifier.py", line 190, in wrapper
confd_base-confd-1     |     return func(*args, **kwargs)
confd_base-confd-1     |   File "/opt/venv/lib/python3.7/site-packages/xivo/auth_verifier.py", line 159, in wrapper
confd_base-confd-1     |     return func(*args, **kwargs)
confd_base-confd-1     |   File "/usr/src/wazo-confd/wazo_confd/plugins/line/resource.py", line 55, in put
confd_base-confd-1     |     self.parse_and_update(model, **kwargs)
confd_base-confd-1     |   File "/usr/src/wazo-confd/wazo_confd/helpers/restful.py", line 133, in parse_and_update
confd_base-confd-1     |     form = self.schema().load(request.get_json(), partial=True)
confd_base-confd-1     |   File "/opt/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 728, in load
confd_base-confd-1     |     data, many=many, partial=partial, unknown=unknown, postprocess=True
confd_base-confd-1     |   File "/opt/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 850, in _do_load
confd_base-confd-1     |     PRE_LOAD, data, many=many, original_data=data, partial=partial
confd_base-confd-1     |   File "/opt/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 1101, in _invoke_load_processors
confd_base-confd-1     |     partial=partial,
confd_base-confd-1     |   File "/opt/venv/lib/python3.7/site-packages/marshmallow/schema.py", line 1227, in _invoke_processors
confd_base-confd-1     |     data = processor(data, many=many, **kwargs)
confd_base-confd-1     |   File "/usr/src/wazo-confd/wazo_confd/plugins/line/schema.py", line 84, in propagate_context
confd_base-confd-1     |     line_context = data['context']
confd_base-confd-1     | KeyError: 'context'
confd_base-confd-1     | 2022-11-09 14:52:06,897 [1] (INFO) (flask.app): response to 172.18.0.1 in 0.02s: PUT http://127.0.0.1:49160/1.1/lines/14 500
confd_base-confd-1     | 2022-11-09 14:52:06,897 [1] (DEBUG) (flask.app): response body: ["Unexpected error: 'context'"]
```

**Review by fblackburn1 — APPROVED** [review]

**Review by fblackburn1 — DISMISSED** [review]

**Pull request merged**
