### PR TITLE
Fix issue with device on user creation

### PR DESCRIPTION
**Pull request by xxbillouxx**
- `FormattedError` is not used as it should be
- Enhance device middleware
- middleware `unallocated_device_middleware` renamed to `device`

### CODE REVIEW

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Review by pc-m — DISMISSED** [review]

**Comment by xxbillouxx** [comment]
recheck

**Comment by xxbillouxx** [comment]
recheck

**Review by pc-m — APPROVED** [review]

**Pull request merged**
