### PR TITLE
WP-876 dhcp validation

### PR DESCRIPTION
**Pull request by DrPyser**
https://wazo-dev.atlassian.net/browse/WP-876

Depends-on: https://github.com/wazo-platform/wazo-sysconfd/pull/82

### CODE REVIEW

**Comment by xxbillouxx** [comment]
https://github.com/wazo-platform/wazo-sysconfd/pull/82 is closed

**Review by xxbillouxx — CHANGES_REQUESTED** [review]
can you add tests covering your new code please ?

**Comment by DrPyser** [comment]
> [wazo-platform/wazo-sysconfd#82](https://github.com/wazo-platform/wazo-sysconfd/pull/82) is closed
> 
> Can you update the dependencies with `Depends-on:` plz ?

Oups, that was an accident, reopened the PR

**Review by xxbillouxx — APPROVED** [review]
LGTM, GJ

**Review by xxbillouxx — DISMISSED** [review]
LGTM, GJ

**Review by xxbillouxx — APPROVED** [review]
LGTM

**Pull request merged**
