### PR TITLE
Pull request for WAZO-2422-switchboard-fallback-noanswer

### PR DESCRIPTION
**Pull request by sduthil**
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/125
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/121
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/41

### CODE REVIEW

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Review by pc-m — APPROVED** [review]

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Pull request merged**
