### PR TITLE
Pull request for WAZO-3685-user-outgoing-callerids

### PR DESCRIPTION
**Pull request by fblackburn1**

### CODE REVIEW

**Review by pc-m — DISMISSED** [review]

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
Fail was due to random conflict with extension generator

**Comment by fblackburn1** [comment]
Flaky test are now fixed by https://github.com/wazo-platform/wazo-confd/pull/455

**Pull request merged**
