### PR TITLE
config: parameterize max number of concurrent requests

### PR DESCRIPTION
**Pull request by sduthil**

### CODE REVIEW

**Review by pc-m — APPROVED** [review]

**Comment by pc-m** [comment]
> Build failed (gate pipeline). For information on how to proceed, see http://docs.openstack.org/infra/manual/developers.html#automated-testing
> 
> * [tox-linters ](https://zuul.wazo.community/zuul/t/local/build/c8aaf4bee6c14359967c23b36feca0c2) : SUCCESS in 3m 56s
> * [wazo-tox-py39 ](https://zuul.wazo.community/zuul/t/local/build/fe22b2c9b89a4507babfe70aa00b51cd) : SUCCESS in 4m 17s
> * [debian-packaging-bullseye ](https://zuul.wazo.community/zuul/t/local/build/b10ebb3ffdf74e5bb105012e23b075aa) : SUCCESS in 2m 51s
> * [confd-tox-integration ](https://zuul.wazo.community/zuul/t/local/build/9bea4fefaf294da4a610467ff194c1b9) : FAILURE in 22m 41s

I've reproduced the fail locally and added more info to the assert
```
    assert expected_count <= actual_count <= expected_count + 1, f'Expected: {expected_count} Count: {actual_count}'
AssertionError: Expected: 5 Count: 7
```

**Comment by pc-m** [comment]
> > Build failed (gate pipeline). For information on how to proceed, see http://docs.openstack.org/infra/manual/developers.html#automated-testing
> > 
> > * [tox-linters ](https://zuul.wazo.community/zuul/t/local/build/c8aaf4bee6c14359967c23b36feca0c2) : SUCCESS in 3m 56s
> > * [wazo-tox-py39 ](https://zuul.wazo.community/zuul/t/local/build/fe22b2c9b89a4507babfe70aa00b51cd) : SUCCESS in 4m 17s
> > * [debian-packaging-bullseye ](https://zuul.wazo.community/zuul/t/local/build/b10ebb3ffdf74e5bb105012e23b075aa) : SUCCESS in 2m 51s
> > * [confd-tox-integration ](https://zuul.wazo.community/zuul/t/local/build/9bea4fefaf294da4a610467ff194c1b9) : FAILURE in 22m 41s
> 
> I've reproduced the fail locally and added more info to the assert
> 
> ```
>     assert expected_count <= actual_count <= expected_count + 1, f'Expected: {expected_count} Count: {actual_count}'
> AssertionError: Expected: 5 Count: 7
> ```

And the last statements are...
```
2023-05-10 13:25:59.106 UTC [23] asterisk@asterisk LOG:  duration: 0.032 ms  statement: BEGIN
2023-05-10 13:25:59.107 UTC [23] asterisk@asterisk LOG:  duration: 0.057 ms  statement: SELECT 1
2023-05-10 13:25:59.107 UTC [23] asterisk@asterisk LOG:  duration: 0.032 ms  statement: SELECT 1
2023-05-10 13:25:59.136 UTC [23] asterisk@asterisk LOG:  duration: 10.242 ms  statement: SELECT linefeatures.id AS linefeatures_id, linefeatures.device AS linefeatures_device, linefeatures.configregistrar AS linefeatures_configregistrar, linefeatures.name AS linefeatures_name, linefeatures.number AS linefeatures_number, linefeatures.context AS linefeatures_context, linefeatures.provisioningid AS linefeatures_provisioningid, linefeatures.num AS linefeatures_num, linefeatures.ipfrom AS linefeatures_ipfrom, linefeatures.application_uuid AS linefeatures_application_uuid, linefeatures.commented AS linefeatures_commented, linefeatures.description AS linefeatures_description, linefeatures.endpoint_sip_uuid AS linefeatures_endpoint_sip_uuid, linefeatures.endpoint_sccp_id AS linefeatures_endpoint_sccp_id, linefeatures.endpoint_custom_id AS linefeatures_endpoint_custom_id, context_1.id AS context_1_id, context_1.tenant_uuid AS context_1_tenant_uuid, context_1.name AS context_1_name, context_1.displayname AS context_1_displayname, context_1.contexttype AS context_1_contexttype, context_1.commented AS context_1_commented, context_1.description AS context_1_description, (SELECT options  FROM endpoint_sip_options_view  WHERE endpoint_sip_1.uuid = root) AS anon_1, endpoint_sip_section_option_1.uuid AS endpoint_sip_section_option_1_uuid, endpoint_sip_section_option_1.key AS endpoint_sip_section_option_1_key, endpoint_sip_section_option_1.value AS endpoint_sip_section_option_1_value, endpoint_sip_section_option_1.endpoint_sip_section_uuid AS endpoint_sip_section_option_1_endpoint_sip_section_uuid, endpoint_sip_section_1.uuid AS endpoint_sip_section_1_uuid, endpoint_sip_section_1.type AS endpoint_sip_section_1_type, endpoint_sip_section_1.endpoint_sip_uuid AS endpoint_sip_section_1_endpoint_sip_uuid, endpoint_sip_section_option_2.uuid AS endpoint_sip_section_option_2_uuid, endpoint_sip_section_option_2.key AS endpoint_sip_section_option_2_key, endpoint_sip_section_option_2.value AS endpoint_sip_section_option_2_value, endpoint_sip_section_option_2.endpoint_sip_section_uuid AS endpoint_sip_section_option_2_endpoint_sip_section_uuid, endpoint_sip_section_2.uuid AS endpoint_sip_section_2_uuid, endpoint_sip_section_2.type AS endpoint_sip_section_2_type, endpoint_sip_section_2.endpoint_sip_uuid AS endpoint_sip_section_2_endpoint_sip_uuid, endpoint_sip_1.uuid AS endpoint_sip_1_uuid, endpoint_sip_1.label AS endpoint_sip_1_label, endpoint_sip_1.name AS endpoint_sip_1_name, endpoint_sip_1.asterisk_id AS endpoint_sip_1_asterisk_id, endpoint_sip_1.tenant_uuid AS endpoint_sip_1_tenant_uuid, endpoint_sip_1.transport_uuid AS endpoint_sip_1_transport_uuid, endpoint_sip_1.template AS endpoint_sip_1_template, sccpline_1.id AS sccpline_1_id, sccpline_1.tenant_uuid AS sccpline_1_tenant_uuid, sccpline_1.name AS sccpline_1_name, sccpline_1.context AS sccpline_1_context, sccpline_1.cid_name AS sccpline_1_cid_name, sccpline_1.cid_num AS sccpline_1_cid_num, sccpline_1.disallow AS sccpline_1_disallow, sccpline_1.allow AS sccpline_1_allow, sccpline_1.protocol AS sccpline_1_protocol, sccpline_1.commented AS sccpline_1_commented, usercustom_1.id AS usercustom_1_id, usercustom_1.tenant_uuid AS usercustom_1_tenant_uuid, usercustom_1.name AS usercustom_1_name, usercustom_1.context AS usercustom_1_context, usercustom_1.interface AS usercustom_1_interface, usercustom_1.intfsuffix AS usercustom_1_intfsuffix, usercustom_1.commented AS usercustom_1_commented, usercustom_1.protocol AS usercustom_1_protocol, usercustom_1.category AS usercustom_1_category, extensions_1.id AS extensions_1_id, extensions_1.commented AS extensions_1_commented, extensions_1.context AS extensions_1_context, extensions_1.exten AS extensions_1_exten, extensions_1.type AS extensions_1_type, extensions_1.typeval AS extensions_1_typeval, line_extension_1.line_id AS line_extension_1_line_id, line_extension_1.extension_id AS line_extension_1_extension_id, line_extension_1.main_extension AS line_extension_1_main_extension, userfeatures_1.email AS userfeatures_1_email, userfeatures_1.lastname AS userfeatures_1_lastname, userfeatures_1.userfield AS userfeatures_1_userfield, userfeatures_1.description AS userfeatures_1_description, userfeatures_1.id AS userfeatures_1_id, userfeatures_1.uuid AS userfeatures_1_uuid, userfeatures_1.firstname AS userfeatures_1_firstname, userfeatures_1.voicemailid AS userfeatures_1_voicemailid, userfeatures_1.agentid AS userfeatures_1_agentid, userfeatures_1.pictureid AS userfeatures_1_pictureid, userfeatures_1.tenant_uuid AS userfeatures_1_tenant_uuid, userfeatures_1.callerid AS userfeatures_1_callerid, userfeatures_1.ringseconds AS userfeatures_1_ringseconds, userfeatures_1.simultcalls AS userfeatures_1_simultcalls, userfeatures_1.enableclient AS userfeatures_1_enableclient, userfeatures_1.loginclient AS userfeatures_1_loginclient, userfeatures_1.passwdclient AS userfeatures_1_passwdclient, userfeatures_1.enablehint AS userfeatures_1_enablehint, userfeatures_1.enablevoicemail AS userfeatures_1_enablevoicemail, userfeatures_1.enablexfer AS userfeatures_1_enablexfer, userfeatures_1.dtmf_hangup AS userfeatures_1_dtmf_hangup, userfeatures_1.enableonlinerec AS userfeatures_1_enableonlinerec, userfeatures_1.call_record_outgoing_external_enabled AS userfeatures_1_call_record_outgoing_external_enabled, userfeatures_1.call_record_outgoing_internal_enabled AS userfeatures_1_call_record_outgoing_internal_enabled, userfeatures_1.call_record_incoming_external_enabled AS userfeatures_1_call_record_incoming_external_enabled, userfeatures_1.call_record_incoming_internal_enabled AS userfeatures_1_call_record_incoming_internal_enabled, userfeatures_1.incallfilter AS userfeatures_1_incallfilter, userfeatures_1.enablednd AS userfeatures_1_enablednd, userfeatures_1.enableunc AS userfeatures_1_enableunc, userfeatures_1.destunc AS userfeatures_1_destunc, userfeatures_1.enablerna AS userfeatures_1_enablerna, userfeatures_1.destrna AS userfeatures_1_destrna, userfeatures_1.enablebusy AS userfeatures_1_enablebusy, userfeatures_1.destbusy AS userfeatures_1_destbusy, userfeatures_1.musiconhold AS userfeatures_1_musiconhold, userfeatures_1.outcallerid AS userfeatures_1_outcallerid, userfeatures_1.mobilephonenumber AS userfeatures_1_mobilephonenumber, userfeatures_1.bsfilter AS userfeatures_1_bsfilter, userfeatures_1.preprocess_subroutine AS userfeatures_1_preprocess_subroutine, userfeatures_1.timezone AS userfeatures_1_timezone, userfeatures_1.language AS userfeatures_1_language, userfeatures_1.ringintern AS userfeatures_1_ringintern, userfeatures_1.ringextern AS userfeatures_1_ringextern, userfeatures_1.ringgroup AS userfeatures_1_ringgroup, userfeatures_1.ringforward AS userfeatures_1_ringforward, userfeatures_1.rightcallcode AS userfeatures_1_rightcallcode, userfeatures_1.commented AS userfeatures_1_commented, userfeatures_1.func_key_template_id AS userfeatures_1_func_key_template_id, userfeatures_1.func_key_private_template_id AS userfeatures_1_func_key_private_template_id, userfeatures_1.subscription_type AS userfeatures_1_subscription_type, userfeatures_1.created_at AS userfeatures_1_created_at, user_line_1.user_id AS user_line_1_user_id, user_line_1.line_id AS user_line_1_line_id, user_line_1.main_user AS user_line_1_main_user, user_line_1.main_line AS user_line_1_main_line  FROM linefeatures LEFT OUTER JOIN line_extension ON line_extension.line_id = linefeatures.id AND linefeatures.commented = 0 LEFT OUTER JOIN extensions ON line_extension.extension_id = extensions.id AND line_extension.line_id = linefeatures.id AND extensions.commented = 0 LEFT OUTER JOIN context AS context_1 ON linefeatures.context = context_1.name LEFT OUTER JOIN endpoint_sip AS endpoint_sip_1 ON endpoint_sip_1.uuid = linefeatures.endpoint_sip_uuid LEFT OUTER JOIN endpoint_sip_section AS endpoint_sip_section_1 ON endpoint_sip_1.uuid = endpoint_sip_section_1.endpoint_sip_uuid AND endpoint_sip_section_1.type IN ('auth') LEFT OUTER JOIN endpoint_sip_section_option AS endpoint_sip_section_option_1 ON endpoint_sip_section_1.uuid = endpoint_sip_section_option_1.endpoint_sip_section_uuid LEFT OUTER JOIN endpoint_sip_section AS endpoint_sip_section_2 ON endpoint_sip_1.uuid = endpoint_sip_section_2.endpoint_sip_uuid AND endpoint_sip_section_2.type IN ('endpoint') LEFT OUTER JOIN endpoint_sip_section_option AS endpoint_sip_section_option_2 ON endpoint_sip_section_2.uuid = endpoint_sip_section_option_2.endpoint_sip_section_uuid LEFT OUTER JOIN sccpline AS sccpline_1 ON sccpline_1.id = linefeatures.endpoint_sccp_id LEFT OUTER JOIN usercustom AS usercustom_1 ON usercustom_1.id = linefeatures.endpoint_custom_id LEFT OUTER JOIN line_extension AS line_extension_1 ON linefeatures.id = line_extension_1.line_id LEFT OUTER JOIN extensions AS extensions_1 ON extensions_1.id = line_extension_1.extension_id LEFT OUTER JOIN user_line AS user_line_1 ON linefeatures.id = user_line_1.line_id LEFT OUTER JOIN userfeatures AS userfeatures_1 ON userfeatures_1.id = user_line_1.user_id  WHERE (SELECT context.tenant_uuid  FROM context  WHERE context.name = linefeatures.context) IN ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee1') ORDER BY linefeatures.name ASC, line_extension_1.main_extension DESC, user_line_1.main_user DESC
2023-05-10 13:25:59.160 UTC [23] asterisk@asterisk LOG:  duration: 0.813 ms  statement: SELECT count(*) AS count_1  FROM (SELECT linefeatures.id AS linefeatures_id, linefeatures.device AS linefeatures_device, linefeatures.configregistrar AS linefeatures_configregistrar, linefeatures.name AS linefeatures_name, linefeatures.number AS linefeatures_number, linefeatures.context AS linefeatures_context, linefeatures.provisioningid AS linefeatures_provisioningid, linefeatures.num AS linefeatures_num, linefeatures.ipfrom AS linefeatures_ipfrom, linefeatures.application_uuid AS linefeatures_application_uuid, linefeatures.commented AS linefeatures_commented, linefeatures.description AS linefeatures_description, linefeatures.endpoint_sip_uuid AS linefeatures_endpoint_sip_uuid, linefeatures.endpoint_sccp_id AS linefeatures_endpoint_sccp_id, linefeatures.endpoint_custom_id AS linefeatures_endpoint_custom_id  FROM linefeatures LEFT OUTER JOIN line_extension ON line_extension.line_id = linefeatures.id AND linefeatures.commented = 0 LEFT OUTER JOIN extensions ON line_extension.extension_id = extensions.id AND line_extension.line_id = linefeatures.id AND extensions.commented = 0  WHERE (SELECT context.tenant_uuid  FROM context  WHERE context.name = linefeatures.context) IN ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee1') ORDER BY linefeatures.name ASC) AS anon_1
2023-05-10 13:25:59.300 UTC [23] asterisk@asterisk LOG:  duration: 128.497 ms  statement: REFRESH MATERIALIZED VIEW CONCURRENTLY endpoint_sip_options_view
2023-05-10 13:25:59.301 UTC [23] asterisk@asterisk LOG:  duration: 0.629 ms  statement: COMMIT
```

**Comment by pc-m** [comment]
> statement: COMMIT

@sduthil do you know if the `pool_pre_ping=True` option adds the `SELECT 1`?

**Comment by pc-m** [comment]
The next run could be a success since the materialized view will be gone

**Review by pc-m — APPROVED** [review]

**Comment by fblackburn1** [comment]
> > statement: COMMIT
> 
> @sduthil do you know if the `pool_pre_ping=True` option adds the `SELECT 1`?

From my memories, yes

**Pull request merged**
