### PR TITLE
Pull request for WP-1276-parking-function-keys

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/267
Depends-on: https://github.com/wazo-platform/xivo-manage-db/pull/250

### CODE REVIEW

**Review by bloom1 — APPROVED** [review]

**Comment by bloom1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck (to see there is a desync, because everything pass locally)

**Comment by fblackburn1** [comment]
Previous fail is fixed by this PR https://github.com/wazo-platform/xivo-dao/pull/270

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
@fblackburn1 any idea why this still fails?

**Pull request merged**
