### PR TITLE
user: do not execute pre_dump for field that are not required

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/29

### CODE REVIEW

**Comment by sboily** [comment]
:hearts:

**Comment by fblackburn1** [comment]
> hearts

Don't be too excited, it was a regression from new code added in this iteration

**Comment by sboily** [comment]
> > hearts
> 
> Don't be too excited, it was a regression from new code added in this iteration

:broken_heart:

**Comment by fblackburn1** [comment]
recheck

**Pull request merged**
