### PR TITLE
WAZO-2505: confd events

### PR DESCRIPTION
**Pull request by ja0x**
Depends-On: https://github.com/wazo-platform/xivo-bus/pull/59

### CODE REVIEW

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Review by pc-m — DISMISSED** [review]

**Review by pc-m — APPROVED** [review]

**Comment by ja0x** [comment]
regate

**Pull request merged**
