### PR TITLE
Add mark_answered_elsewhere on groups and queues

### PR DESCRIPTION
**Pull request by bloom1**
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/35
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/33

### CODE REVIEW

**Comment by bloom1** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Pull request merged**
